### ISSUE TITLE
input image dimension should be 1 not 3

### ISSUE THREAD

**Issue by themeewa** [msadegh97/CheXNet-implementation-in-Keras#1]
why are we making our image 3 times heavy before processing. x ray images have 1 channel, how are we making t 3 channel image and why?

**Comment by msadegh97** [comment]
CheXNet paper uses dense121 architecture to extract feature maps. Also, I want to use the pre-train dense net implementation in keras. Dense121 train on three channel images of the imagenet dataset so for compatibility our network with our dataset I convert X-ray images to RGB format.

**Comment by msadegh97** [comment]
Hope you're great. Just sending you a gentle reminder on my internship
request.

I'm sure you must be really busy, and I don't want to seem interrupting.

Also, I want to ask how long does it take to clarify my request?

I look forward to hearing from you and thanks you in advance.

Sincerely, Mohammad Sadegh
